/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JGlucose */

#ifndef _Included_JGlucose
#define _Included_JGlucose
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JGlucose
 * Method:    ginit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JGlucose_ginit
  (JNIEnv *, jclass);

/*
 * Class:     JGlucose
 * Method:    gadd
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_JGlucose_gadd
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     JGlucose
 * Method:    gsat
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_JGlucose_gsat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     JGlucose
 * Method:    gderef
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_JGlucose_gderef
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
