#!/bin/bash

cd jdrasil/src
if [ "$1" == "-s" ]; then
    /usr/lib/jvm/java-8-openjdk-amd64/bin/java  -cp ../../lib/glucose.jar:../../lib/glucosep.jar:../../lib/pblib.jar:. -Djava.library.path=../../lib/glucose/simp/:../../lib/glucose/parallel:../../lib/pblib de.uniluebeck.tcs.App  -parallel -s $2  -e PBLib_incremental <&0 &
else
    /usr/lib/jvm/java-8-openjdk-amd64/bin/java  -cp ../../lib/glucose.jar:../../lib/glucosep.jar:../../lib/pblib.jar:. -Djava.library.path=../../lib/glucose/simp/:../../lib/glucose/parallel:../../lib/pblib de.uniluebeck.tcs.App  -parallel  -e PBLib_incremental <&0 &
fi

PID=$!
trap "kill -SIGUSR2 $PID" SIGUSR1
trap "kill -9 $PID" SIGTERM

while :
do
    wait $PID
    kill -0 $PID 2> /dev/null || break
done



