/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Darwin Donatra 16.1.0 x86_64"
#define LGL_COMPILED "Sat Dec  3 16:36:49 CET 2016"
#define LGL_RELEASED "Thu Jul  7 10:21:35 CEST 2016"
#define LGL_VERSION "bbc"
#define LGL_ID "923038088b727dcc8bd03aa8dfb5013bd03bf8c4"
