/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pseudo_PBLib */

#ifndef _Included_pseudo_PBLib
#define _Included_pseudo_PBLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pseudo_PBLib
 * Method:    generateAtMostK
 * Signature: ([IIII)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_pseudo_PBLib_generateAtMostK
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     pseudo_PBLib
 * Method:    generateAtLeastK
 * Signature: ([IIII)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_pseudo_PBLib_generateAtLeastK
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     pseudo_PBLib
 * Method:    initIterAtMostK
 * Signature: ([IIIIJ)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_pseudo_PBLib_initIterAtMostK
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong);

/*
 * Class:     pseudo_PBLib
 * Method:    initIterAtLeastK
 * Signature: ([IIIIJ)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_pseudo_PBLib_initIterAtLeastK
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong);

/*
 * Class:     pseudo_PBLib
 * Method:    citerAtMostK
 * Signature: (IIJ)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_pseudo_PBLib_citerAtMostK
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     pseudo_PBLib
 * Method:    citerAtLeastK
 * Signature: (IIJ)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_pseudo_PBLib_citerAtLeastK
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     pseudo_PBLib
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_pseudo_PBLib_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
