/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdrasil_sat_NativeSATSolver */

#ifndef _Included_jdrasil_sat_NativeSATSolver
#define _Included_jdrasil_sat_NativeSATSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    signature
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jdrasil_sat_NativeSATSolver_signature
  (JNIEnv *, jobject);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdrasil_sat_NativeSATSolver_init
  (JNIEnv *, jobject);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdrasil_sat_NativeSATSolver_release
  (JNIEnv *, jobject);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    add
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jdrasil_sat_NativeSATSolver_add
  (JNIEnv *, jobject, jint);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    assume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jdrasil_sat_NativeSATSolver_assume
  (JNIEnv *, jobject, jint);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    solve
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jdrasil_sat_NativeSATSolver_solve
  (JNIEnv *, jobject);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    val
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jdrasil_sat_NativeSATSolver_val
  (JNIEnv *, jobject, jint);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    failed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jdrasil_sat_NativeSATSolver_failed
  (JNIEnv *, jobject, jint);

/*
 * Class:     jdrasil_sat_NativeSATSolver
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdrasil_sat_NativeSATSolver_terminate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
